services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lab1
      POSTGRES_PASSWORD: lab1
      POSTGRES_DB: lab1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab1 -d lab1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      DB_USER: lab1
      DB_PASSWORD: lab1
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: lab1
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
